#ifndef JSON_PARSER_ERROR_CODES_H
#define JSON_PARSER_ERROR_CODES_H

#define JSON_NO_ERROR          0
#define JSON_LEXER_ERROR      -1
#define JSON_PARSER_ERROR     -2
#define JSON_ERROR_IN_STREAM  -3
#define JSON_ALLOCATION_ERROR -4

#endif